<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyTracNghiemHocSinh-LTQLUD" Class="DataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-VBJGI2B\SQLEXPRESS;Initial Catalog=QuanLyTracNghiemHocSinh-LTQLUD;Integrated Security=True" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="QuanLyTracNghiemHocSinh_LTQLUDConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CauHoi" Member="CauHois">
    <Type Name="CauHoi">
      <Column Name="MaCauHoi" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CauA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CauB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CauC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CauD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CauDung" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="MaKhoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HocSinhDongGop" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DoKho" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CauHoi_CauHoiTrongDeNao" Member="CauHoiTrongDeNaos" ThisKey="MaCauHoi" OtherKey="MaCauHoi" Type="CauHoiTrongDeNao" />
      <Association Name="DoKho_CauHoi" Member="DoKho1" ThisKey="DoKho" OtherKey="maDoKho" Type="DoKho" IsForeignKey="true" />
      <Association Name="Khoi_CauHoi" Member="Khoi" ThisKey="MaKhoi" OtherKey="MaKhoi" Type="Khoi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CauHoiTrongDeNao" Member="CauHoiTrongDeNaos">
    <Type Name="CauHoiTrongDeNao">
      <Column Name="MaCauHoi" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDe" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKhoi" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CauHoi_CauHoiTrongDeNao" Member="CauHoi" ThisKey="MaCauHoi" OtherKey="MaCauHoi" Type="CauHoi" IsForeignKey="true" />
      <Association Name="De_CauHoiTrongDeNao" Member="De" ThisKey="MaDe,MaKhoi" OtherKey="MaDe,MaKhoi" Type="De" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.De" Member="Des">
    <Type Name="De">
      <Column Name="MaDe" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaKhoi" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DoKho" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="De_CauHoiTrongDeNao" Member="CauHoiTrongDeNaos" ThisKey="MaDe,MaKhoi" OtherKey="MaDe,MaKhoi" Type="CauHoiTrongDeNao" />
      <Association Name="De_DeOnTap" Member="DeOnTaps" ThisKey="MaDe,MaKhoi" OtherKey="MaDe,MaKhoi" Type="DeOnTap" />
      <Association Name="De_DeVaKhoiTrongKyThi" Member="DeVaKhoiTrongKyThis" ThisKey="MaDe,MaKhoi" OtherKey="MaDe,MaKhoi" Type="DeVaKhoiTrongKyThi" />
      <Association Name="Khoi_De" Member="Khoi" ThisKey="MaKhoi" OtherKey="MaKhoi" Type="Khoi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeOnTap" Member="DeOnTaps">
    <Type Name="DeOnTap">
      <Column Name="MaHocSinh" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDe" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKhoi" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayGioiHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Diem" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="De_DeOnTap" Member="De" ThisKey="MaDe,MaKhoi" OtherKey="MaDe,MaKhoi" Type="De" IsForeignKey="true" />
      <Association Name="HocSinh_DeOnTap" Member="HocSinh" ThisKey="MaHocSinh" OtherKey="MaHocSinh" Type="HocSinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeVaKhoiTrongKyThi" Member="DeVaKhoiTrongKyThis">
    <Type Name="DeVaKhoiTrongKyThi">
      <Column Name="MaDeVaKhoiTrongKyThi" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDe" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaKhoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaKyThi" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="DeVaKhoiTrongKyThi_HocSinhTrongKiThi" Member="HocSinhTrongKiThis" ThisKey="MaDeVaKhoiTrongKyThi" OtherKey="MaDeVaKhoiTrongKiThi" Type="HocSinhTrongKiThi" />
      <Association Name="De_DeVaKhoiTrongKyThi" Member="De" ThisKey="MaDe,MaKhoi" OtherKey="MaDe,MaKhoi" Type="De" IsForeignKey="true" />
      <Association Name="KyThi_DeVaKhoiTrongKyThi" Member="KyThi" ThisKey="MaKyThi" OtherKey="MaKyThi" Type="KyThi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DoKho" Member="DoKhos">
    <Type Name="DoKho">
      <Column Name="maDoKho" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDoKho" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DoKho_CauHoi" Member="CauHois" ThisKey="maDoKho" OtherKey="DoKho" Type="CauHoi" />
    </Type>
  </Table>
  <Table Name="dbo.GiaoVien" Member="GiaoViens">
    <Type Name="GiaoVien">
      <Column Name="MaGiaVien" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaKhoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Khoi_GiaoVien" Member="Khoi" ThisKey="MaKhoi" OtherKey="MaKhoi" Type="Khoi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HocSinh" Member="HocSinhs">
    <Type Name="HocSinh">
      <Column Name="MaHocSinh" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="SoilPass" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Association Name="HocSinh_DeOnTap" Member="DeOnTaps" ThisKey="MaHocSinh" OtherKey="MaHocSinh" Type="DeOnTap" />
      <Association Name="HocSinh_HocSinhTrongKiThi" Member="HocSinhTrongKiThis" ThisKey="MaHocSinh" OtherKey="MaHocSinh" Type="HocSinhTrongKiThi" />
      <Association Name="Lop_HocSinh" Member="Lop" ThisKey="MaLop" OtherKey="MaLop" Type="Lop" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HocSinhTrongKiThi" Member="HocSinhTrongKiThis">
    <Type Name="HocSinhTrongKiThi">
      <Column Name="MaHocSinh" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDeVaKhoiTrongKiThi" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Diem" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="DeVaKhoiTrongKyThi_HocSinhTrongKiThi" Member="DeVaKhoiTrongKyThi" ThisKey="MaDeVaKhoiTrongKiThi" OtherKey="MaDeVaKhoiTrongKyThi" Type="DeVaKhoiTrongKyThi" IsForeignKey="true" />
      <Association Name="HocSinh_HocSinhTrongKiThi" Member="HocSinh" ThisKey="MaHocSinh" OtherKey="MaHocSinh" Type="HocSinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Khoi" Member="Khois">
    <Type Name="Khoi">
      <Column Name="MaKhoi" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhoi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Khoi_CauHoi" Member="CauHois" ThisKey="MaKhoi" OtherKey="MaKhoi" Type="CauHoi" />
      <Association Name="Khoi_De" Member="Des" ThisKey="MaKhoi" OtherKey="MaKhoi" Type="De" />
      <Association Name="Khoi_GiaoVien" Member="GiaoViens" ThisKey="MaKhoi" OtherKey="MaKhoi" Type="GiaoVien" />
      <Association Name="Khoi_Lop" Member="Lops" ThisKey="MaKhoi" OtherKey="MaKhoi" Type="Lop" />
    </Type>
  </Table>
  <Table Name="dbo.KyThi" Member="KyThis">
    <Type Name="KyThi">
      <Column Name="MaKyThi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKyThi" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NgayThi" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="KyThi_DeVaKhoiTrongKyThi" Member="DeVaKhoiTrongKyThis" ThisKey="MaKyThi" OtherKey="MaKyThi" Type="DeVaKhoiTrongKyThi" />
    </Type>
  </Table>
  <Table Name="dbo.Lop" Member="Lops">
    <Type Name="Lop">
      <Column Name="MaLop" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaKhoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Lop_HocSinh" Member="HocSinhs" ThisKey="MaLop" OtherKey="MaLop" Type="HocSinh" />
      <Association Name="Khoi_Lop" Member="Khoi" ThisKey="MaKhoi" OtherKey="MaKhoi" Type="Khoi" IsForeignKey="true" />
    </Type>
  </Table>
</Database>